### ISSUE TITLE
Create dependabot config file

### ISSUE THREAD

**Issue by MateuszKepczynski** [MateuszKepczynski/Go-Save-Eyes#9]
Create config file "dependabot.yml" for dependabot under .github/ folder.

Template:
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
